In [14]:
%matplotlib inline
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from IPython.display import display,Markdown
import os

In [2]:
engine=create_engine("mysql+mysqlconnector://root:root@localhost/store")

In [15]:
api_key=os.environ.get("GOOGLE_API_KEY")
llm=ChatGoogleGenerativeAI(model='gemini-2.5-flash')

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

### PREVIEW OF THE DATASET

In [4]:
query="SELECT * FROM superstore LIMIT 5"
table_ten=pd.read_sql(query,engine)
table_ten

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters by Universal,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### NUMBER OF REGISTERS

In [5]:
query="SELECT 'Registros',count(*) as total from superstore;"
display(pd.read_sql(query,engine))

   Registros  total
0  Registros   9694

### ANALYZING NULL VALUES

In [6]:
query=""" 
    SELECT 'Row ID' as Columna,SUM(CASE WHEN 'Row ID' IS NULL THEN 1 ELSE 0 END) AS Nulos FROM superstore UNION ALL
    SELECT 'Order Date', SUM(CASE WHEN 'Order Date' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Ship Date', SUM(CASE WHEN 'Ship Date' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Ship Mode', SUM(CASE WHEN 'Ship Mode' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Customer ID', SUM(CASE WHEN 'Customer ID' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Customer Name', SUM(CASE WHEN 'Customer Name' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Segment', SUM(CASE WHEN 'Segment' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Country', SUM(CASE WHEN 'Country' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'City', SUM(CASE WHEN 'City' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'State', SUM(CASE WHEN 'State' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Postal Code', SUM(CASE WHEN 'Postal Code' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Region', SUM(CASE WHEN 'Region' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Product ID', SUM(CASE WHEN 'Order Date' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Category', SUM(CASE WHEN 'Category' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Sub-Category', SUM(CASE WHEN 'Sub-Category' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Sales', SUM(CASE WHEN 'Sales' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Quantity', SUM(CASE WHEN 'Quantity' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Discount', SUM(CASE WHEN 'Discount' IS NULL THEN 1 ELSE 0 END) FROM superstore UNION ALL
    SELECT 'Profit', SUM(CASE WHEN 'Profit' IS NULL THEN 1 ELSE 0 END) FROM superstore;
"""
null_values=pd.read_sql(query,engine)
null_values

          Columna  Nulos
0          Row ID    0.0
1      Order Date    0.0
2       Ship Date    0.0
3       Ship Mode    0.0
4     Customer ID    0.0
5   Customer Name    0.0
6         Segment    0.0
7         Country    0.0
8            City    0.0
9           State    0.0
10    Postal Code    0.0
11         Region    0.0
12     Product ID    0.0
13       Category    0.0
14   Sub-Category    0.0
15          Sales    0.0
16       Quantity    0.0
17       Discount    0.0
18         Profit    0.0

### ANALYZING UNIQUE VALUES

In [7]:
query="DESCRIBE superstore;"
display(pd.read_sql(query,engine))

            Field    Type Null Key Default Extra
0          Row ID     int  YES        None
1        Order ID    text  YES        None
2      Order Date    text  YES        None
3       Ship Date    text  YES        None
4       Ship Mode    text  YES        None
5     Customer ID    text  YES        None
6   Customer Name    text  YES        None
7         Segment    text  YES        None
8         Country    text  YES        None
9            City    text  YES        None
10          State    text  YES        None
11    Postal Code     int  YES        None
12         Region    text  YES        None
13     Product ID    text  YES        None
14       Category    text  YES        None
15   Sub-Category    text  YES        None
16   Product Name    text  YES        None
17          Sales  double  YES        None
18       Quantity     int  YES        None
19       Discount  double  YES        None
20         Profit  double  YES        None

In [8]:
query1="SELECT `Order Date`, count(*) AS total FROM superstore group by `Order Date` ORDER BY total DESC"
query2="SELECT `Ship Date`, count(*) AS total FROM superstore group by `Ship Date` ORDER BY total DESC"
query3="SELECT `Ship Mode`, count(*) AS total FROM superstore group by `Ship Mode` ORDER BY total DESC"
query4="SELECT `Customer ID`, count(*) AS total FROM superstore group by `Customer ID` ORDER BY total DESC"
query5="SELECT `Customer Name`, count(*) AS total FROM superstore group by `Customer Name` ORDER BY total DESC"
query6="SELECT `Segment`, count(*) AS total FROM superstore group by `Segment` ORDER BY total DESC"
query7="SELECT `Country`, count(*) AS total FROM superstore group by `Country` ORDER BY total DESC"
query8="SELECT `City`, count(*) AS total FROM superstore group by `City` ORDER BY total DESC"
query9="SELECT `State`, count(*) AS total FROM superstore group by `State` ORDER BY total DESC"
query10="SELECT `Region`, count(*) AS total FROM superstore group by `Region` ORDER BY total DESC"
query11="SELECT `Category`, count(*) AS total FROM superstore group by `Category` ORDER BY total DESC"
query12="SELECT `Sub-Category`, count(*) AS total FROM superstore group by `Sub-Category` ORDER BY total DESC"
query13="SELECT `Quantity`, count(*) AS total FROM superstore group by `Quantity` ORDER BY total DESC"


display(pd.read_sql(query13,engine))

    Quantity  total
0          3   2335
1          2   2331
2          5   1195
3          4   1148
4          1    874
5          7    591
6          6    553
7          9    252
8          8    250
9         10     55
10        11     34
11        14     28
12        13     26
13        12     22

### OBTAINING THE DATASET

In [12]:
query="SELECT * FROM superstore;"
df=pd.read_sql(query,engine)
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters by Universal,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### ANALYZING THE DATASET WITH LLM

In [19]:
df_dict=df.sample(n=500)
df_dict=df_dict.to_dict(orient='records')
template = ChatPromptTemplate.from_messages([
    ("system",
    """You are a senior data scientist.

Your task is to provide a HIGH-LEVEL description of a dataset.

STRICT RULES:
- Describe ONLY the general purpose of the dataset.
- Do NOT analyze relationships between variables.
- Do NOT infer patterns, trends, or insights.
- Do NOT make assumptions beyond the given data.
- Do NOT suggest visualizations, questions, or next steps.
- Keep the response concise.

COLUMN DESCRIPTION RULES:
- Briefly describe each column in a general way.
- Focus only on what the column represents (e.g., identifier, category, measurement).
- Do NOT interpret meaning beyond the column name and sample values.
- Do NOT compare columns or explain relationships.

FOCUS ON:
- The general domain (e.g., healthcare, finance, e-commerce)
- The type of entities or observations recorded
- The kind of information captured

OUTPUT FORMAT:
- First, a short paragraph (2–4 sentences) describing the dataset overall.
- Then, a bullet list with each column and a brief description.
- Use a clear and neutral tone.
"""),

    ("user",
    """Dataset sample:
{dataset}

Provide a general description of this dataset and its columns.
""")
])
chain=template|llm
response=chain.invoke({"dataset":df_dict})
display(Markdown(response.content))

This dataset contains records of individual sales transactions, likely from a retail or e-commerce business. Each entry represents a specific product item included in a customer's order. It captures details about the order, the product purchased, the customer, and associated financial metrics.

*   **Row ID**: A unique identifier for each individual record in the dataset.
*   **Order ID**: An identifier for the specific customer order.
*   **Order Date**: The date when the order was placed.
*   **Ship Date**: The date when the product was shipped.
*   **Ship Mode**: The shipping method used for the order.
*   **Customer ID**: An identifier for the customer who placed the order.
*   **Customer Name**: The name of the customer.
*   **Segment**: The customer segment to which the customer belongs.
*   **Country**: The country where the customer is located.
*   **City**: The city where the customer is located.
*   **State**: The state where the customer is located.
*   **Postal Code**: The postal code of the customer's location.
*   **Region**: The geographical region associated with the customer's location.
*   **Product ID**: An identifier for the specific product.
*   **Category**: The main category of the product.
*   **Sub-Category**: A more specific sub-category of the product.
*   **Product Name**: The name of the product.
*   **Sales**: The sales amount for the product in this transaction.
*   **Quantity**: The number of units of the product purchased.
*   **Discount**: The discount applied to the product in this transaction.
*   **Profit**: The profit generated from the product in this transaction.

## EXPLORATORY DATA ANALYSIS